repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.5
    hooks:
      - id: golangci-lint
        args: ["./src/...", "--timeout=5m"]
        files: ^src/.*\.go$
        always_run: true
        pass_filenames: false

  - repo: local
    hooks:
      - id: go-unit-tests
        name: Run Go Unit Tests
        entry: go test ./src/...
        language: system
        pass_filenames: false
        always_run: true
