FROM golang:1.25-alpine AS builder

# Alpine
RUN apk add --no-cache git build-base
# Debian
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     git build-essential \
#  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy and download dependencies from root module
COPY go.mod go.sum ./
RUN go mod download

# Copy and download dependencies from server gin module
COPY ./src/infrastructure/server/go.mod ./src/infrastructure/server/go.sum ./src/infrastructure/server/
WORKDIR /app/src/infrastructure/server
RUN go mod download

# Copy all source code
WORKDIR /app
COPY ./src ./src
COPY .air.toml ./

# Install necessary tools
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install github.com/air-verse/air@v1.61.7


FROM golang:1.25-alpine

# RUN groupadd -r appuser && useradd -r -g appuser appuser

WORKDIR /app

COPY --from=builder /go/bin/air /usr/local/bin/air
COPY --from=builder /go/bin/dlv /usr/local/bin/dlv

COPY --from=builder /app .

# RUN chown -R appuser:appuser /app

# USER appuser

EXPOSE 8080 40000
