definitions:
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      status:
        type: string
    type: object
  models.UserCreate:
    properties:
      email:
        type: string
      name:
        type: string
      phone:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/health-check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - Health Check
  /api/user:
    post:
      consumes:
      - application/json
      description: This endpoint Create a new user
      parameters:
      - description: Datos del usuario
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UserCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Usuario creado
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Error de validación
          schema:
            additionalProperties:
              type: string
            type: object
      summary: This endpoint Create a new user
      tags:
      - User
swagger: "2.0"
